### ISSUE TITLE
Stolen Sprites

### ISSUE THREAD

**Issue by 3Snake3** [XenoForce/opmod#1]
This mod contains stolen sprites from Sapphirium.

**Comment by 3Snake3** [comment]
> This mod contains stolen sprites from Sapphirium.

Also their names

**Comment by XenoForce** [comment]
> This mod contains stolen sprites from Sapphirium.

> Also their names

Can you be more specific please?

Which sprites?

Which names?

TY.

**Comment by 3Snake3** [comment]
> 
> > This mod contains stolen sprites from Sapphirium.
> 
> > Also their names
> 
> Can you be more specific please?
> 
> Which sprites?
> 
> Which names?
> 
> TY.
> 
> 
> 
Cores
Cage, Scarlet Gem, Indigo(Changed the name in last update), reinforced Indigo(Changed the name in last update), Victory, Triumph, Ocean

**Comment by XenoForce** [comment]
1. The "credits.txt" file was updated to give credit to the Sapphirium mod, and its author. Rather late than never. Sorry about the initial omission.

2. The "opmod" mod has been permanently removed from the in-game Mod Browser. Nobody should ever have access to this completely broken mod.

3. In the end, the GPLv3 license agreement was never violated. So, hopefully all is fine, going forward.
